---
# Playbook pour installer des packages
- name: Configuration de deux serveuris web
  hosts: serverAB
  become: true
  become_user: root

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer le paquet web
      apt:
        name: "apache-2"
        state: present

    - name: Installer le paquet mysql
      apt:
        name: "mysql-server"
        state: present

- name: Configuration serveurC
  hosts: serverC
  become: true
  become_user: root

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer GIT
      apt:
        name: "git"
        state: present

    - name: Installer nginx 
      apt:
        name: "nginx"
        state: present


