---
# Playbook pour installer des packages
- name: Configuration docker
  hosts: serverC
  become: true
  become_user: root

  tasks:
    - name: Mettre à jour la liste des paquets
      apt:
        update_cache: yes

    - name: Installer docker
      apt:
        name: "docker"
        state: present

