 ---
- name: Installer et configurer wordpress
  hosts: db
  become: true
  become_user: root

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.mysql
  
  wp_database:
    name: "wordpress"
    username: "wordpress"
    password: "wordpress"

  Tasks:
    - name: "create wordpress database"
      community.mysql.mysql_db:
        db: "{{ wp_database.name }}"
        state: "present"

    - name: "create user for wordpress databse"
      community.mysql.mysql.user:
        name: "{{ wp_database.username }}"
        password: "{{ wp_database.password }}"
        priv: "{{ wp_database.name }}.*:ALL"
        state: "present"
      with_items: "{{ mysqldb.hosts }}"


    

