---
# Playbook pour installer des packages
- name: Configuration docker
  hosts: servers
  become: true
  become_user: root
  tasks:
    - name: Include tp4 tasks
      include_tasks: tp4/tp4.yml
    - name: Include tp3 tasks
      include_tasks: tp3/tp3.yml
    - name: "message"
      ansible.builtin.debug:
        msg: "il est 10h le 17/06/2025 "
    - name: "ecriture"
      ansible.builtin.template:
        src: "source.j2"
        dest: "/etc/last_changed"
        mode: "0644"





